name: apply-sh-gh-runner-config
on: 
  push:

jobs:
  apply-terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: self-hosted-gh-runners/terraform
    env:
      OS_CLIENT_CONFIG_FILE: ${{ github.workspace }}/clouds.yaml
    outputs:
      RUN_ANSIBLE_OUTPUT: ${{steps.check_hosts.outputs.RUN_ANSIBLE}}
      RUN_ANSIBLE_TEST: ${{ steps.check_hosts.outputs.RUN_ANSIBLE_TEST}}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create clouds.yaml
        run: echo "${{ secrets.OPENSTACK_CLOUDS }}" >> ${{ github.workspace }}/clouds.yaml

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.3
          terraform_wrapper: false

      - name: Terraform init
        run: terraform init

      - name: Terraform plan
        run: terraform plan -out=tfplan 1> /dev/null

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan 1> /dev/null

      - name: Check length of VM List
        id: check_hosts
        run: |
          echo "RUN_ANSBILE=$(echo $(terraform output -json vm_ips) | jq -e 'length > 0')" >> "$GITHUB_OUTPUT" \
          && echo "RUN_ANSIBLE_TEST=THIS_IS_A_TEST" >> "GITHUB_OUTPUT"
          
      
      - name: Create hosts.ini
        run: |
          echo $(terraform output -json vm_ips) | jq -r '.[]' >> ../ansible/hosts.ini

      - name: "!!! DESTROY TERRAFORM WHILE TESTING !!!"
        run: terraform destroy --auto-approve 1> /dev/null
  
  test-output:
    runs-on: ubuntu-latest
    needs: apply-terraform
    env:
      RUN_ANSIBLE_OUTPUT: ${{ needs.apply-terraform.outputs.RUN_ANSIBLE_OUTPUT }}
      RUN_ANSIBLE_TEST: ${{ needs.apply-terraform.outputs.RUN_ANSIBLE_TEST }}
    steps:
      - name: test
        run: |
          echo "${{ env.RUN_ANSIBLE }}" && echo "${{ env.RUN_ANSBILE_TEST }}"

  # apply-gh-action-ansible:
  #   if: ${{ $needs.apply-terraform.outputs.run-ansible }}
  #   runs-on: ubuntu-lastest