name: apply-sh-gh-runner-config
on: 
  workflow-dispatch:

jobs:
  apply-terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: self-hosted-gh-runners/static/terraform
    outputs:
      run-ansible: ${{ steps.check-vms.outputs.run-ansible }}
      vm-ips: ${{ steps.check-vms.outputs.vm-ips }}
    env:
      OS_CLIENT_CONFIG_FILE: ${{ github.workspace }}/clouds.yaml
      IMAGE_NAME: gh-action-runner-image
      FLAVOR_NAME: l3.nano
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create clouds.yaml
        run: echo "${{ secrets.OPENSTACK_CLOUDS }}" >> ${{ github.workspace }}/clouds.yaml

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.3
          terraform_wrapper: false

      - name: Terraform init
        run: terraform init

      - name: Terraform plan
        run: terraform plan -out=tfplan 1> /dev/null

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan 1> /dev/null

      - name: Check length of VM List
        id: check-vms
        run: |
          echo "run-ansible=$(echo $(terraform output -json vm_ips) | jq -e 'length > 0')" >> "$GITHUB_OUTPUT" \
          && echo $(terraform output -json vm_ips) | jq -r '.[]' >> ../ansible/hosts.ini \
          && export VM_IPS=$(echo $(terraform output -json vm_ips) | jq -r '.[]')

      - name: Setup SSH
        run: |
          service ssh status
          eval `ssh-agent -s`
          mkdir -p /home/runner/.ssh/
          touch /home/runner/.ssh/config
          touch /home/runner/.ssh/id_rsa
          echo -e "${{ secrets.FASE_SSH_KEY }}" > /home/runner/.ssh/id_rsa
          chmod 700 /home/runner/.ssh/id_rsa
          ssh-keyscan -H ${{ env.VM_IPS }} >> /home/ubuntu/.ssh/known_hosts

      - name: Run VM setup playbook # Include any environment variables needed
        run: |
          ansible-playbook --private-key /home/runner/.ssh/id_rsa -u ${{ secrets.ANSIBLE_DEPLOY_USER }} -i ../ansible/hosts.ini ../ansible/ansible_install_packages.yaml 

      - name: Run GitHub runner setup playbook # Include any environment variables needed
        run: |
          ansible-playbook --private-key /home/runner/.ssh/id_rsa -u ${{ secrets.ANSIBLE_DEPLOY_USER }} -i ../ansible/hosts.ini ../ansible/ansible_install_github_actions_runner.yaml
      


