name: apply-sh-gh-runner-config
on: 
  push:

jobs:
  apply-terraform:
    runs-on: ubuntu-latest
    env:
      OS_CLIENT_CONFIG_FILE: ${{ github.workspace }}/clouds.yaml
    outputs:
      run-ansible: ${{steps.step6.outputs.run-ansible}}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create clouds.yaml
        run: $(echo ${{ secrets.OPENSTACK_CLOUDS }}) >> ${{ github.workspace }}/clouds.yaml

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.3

      - name: Terraform init
        working-directory: self-hosted-gh-runners/terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: self-hosted-gh-runners/terraform
        run: terraform plan

      - name: Terraform Apply
        working-directory: self-hosted-gh-runners/terraform
        run: terraform apply - auto-approve
      
      - name: Get VM IPs
        run: |
          $(echo "$(terraform output -json vm_ips)" | jq -e 'length > 0' \
          && echo "$(terraform output -json vm_ips)" | jq -r '[]' >> ../ansible/hosts.ini) >> "$GITHUB_OUTPUT"
        
      - name: "!!! DESTROY TERRAFORM WHILE TESTING !!!"
        working-directory: self-hosted-gh-runners/terraform
        run: terraform destroy --auto-approve
  
  test-output:
    runs-on: ubuntu-latest
    needs: apply-terraform
    env:
      RUN_ANSIBLE: ${{ needs.apply-terraform.outputs.run-ansible}}
    steps:
      - name: test
        run: |
          echo ${RUN_ANSIBLE}

  # apply-gh-action-ansible:
  #   if: ${{ $needs.apply-terraform.outputs.run-ansible }}
  #   runs-on: ubuntu-lastest